package com.ktogroup.ktoggle.commons.exception;

public enum MessageCode {
    VALIDATION_ERROR,
    ENTITY_NOT_FOUND,
    ENTITY_ALREADY_EXISTS,
    CONCURRENT_MODIFICATION,
    ENTITY_IN_USE,
    INVALID_CONDITION,
    INVALID_VALUE,
    BUNDLE_INTEGRITY_VIOLATION,
    UNSUPPORTED_EVALUATOR,
    UNKNOWN_CLIENT_KEY,
    DRAFT_CONFLICT,
    DRAFT_CLOSED,
    REVIEW_REQUIRED,
    NOTHING_TO_PUBLISH,
    NOT_ALLOWED,
    UPSTREAM_ERROR,
    UNEXPECTED_ERROR
}
