// Seeds the LOCAL, disposable GrowthBook started with `docker compose --profile growthbook up -d`.
// It holds sample data only (no KTO data) and exists to demonstrate the ktoggle importer and shadow comparison.
//
//   node local-infra/growthbook/seed.mjs
//
// Creates (once) the local admin, a secret API key written to local-infra/growthbook/local.env (git-ignored), and
// a set of features, saved groups and SDK connections through GrowthBook's public REST API (/api/v1).
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const API = process.env.GROWTHBOOK_API ?? 'http://localhost:3400'
const ADMIN = { email: 'admin@growthbook.local', password: 'growthbook-local-admin', name: 'Local admin' }
const ENV_FILE = join(dirname(fileURLToPath(import.meta.url)), 'local.env')

async function call(method, path, body, headers) {
  const response = await fetch(API + path, {
    method,
    headers: { 'Content-Type': 'application/json', ...headers },
    body: body === undefined ? undefined : JSON.stringify(body),
  })
  const text = await response.text()
  const json = text ? JSON.parse(text) : {}
  if (!response.ok || (json.status && json.status >= 400)) {
    throw new Error(`${method} ${path} -> ${response.status} ${text.slice(0, 300)}`)
  }
  return json
}

async function adminSession() {
  const { hasOrganizations } = await call('GET', '/auth/hasorgs')
  const auth = hasOrganizations
    ? await call('POST', '/auth/login', { email: ADMIN.email, password: ADMIN.password })
    : await call('POST', '/auth/firsttime', { ...ADMIN, companyname: 'ktoggle demo' })
  const user = await call('GET', '/user', undefined, { Authorization: `Bearer ${auth.token}` })
  return { Authorization: `Bearer ${auth.token}`, 'X-Organization': user.organizations[0].id }
}

async function secretKey() {
  if (existsSync(ENV_FILE)) {
    const match = readFileSync(ENV_FILE, 'utf8').match(/KTOGGLE_GROWTHBOOK_SECRET_KEY=(\S+)/)
    if (match) return match[1]
  }
  const session = await adminSession()
  const { key } = await call('POST', '/keys', { description: 'ktoggle importer (local)', type: 'admin' }, session)
  writeFileSync(ENV_FILE, [
    '# Local GrowthBook only (docker compose --profile growthbook). Generated by seed.mjs; not a KTO credential.',
    'KTOGGLE_GROWTHBOOK_API_HOST=http://growthbook:3100',
    `KTOGGLE_GROWTHBOOK_SECRET_KEY=${key.key}`,
    'KTOGGLE_GROWTHBOOK_SHADOW_ENABLED=true',
    'KTOGGLE_GROWTHBOOK_SHADOW_INTERVAL=PT2M',
    '',
  ].join('\n'))
  return key.key
}

const key = await secretKey()
const v1 = (method, path, body) => call(method, `/api/v1${path}`, body, { Authorization: `Bearer ${key}` })

const existing = new Set(((await v1('GET', '/features?limit=100')).features ?? []).map((f) => f.id))
const createFeature = async (feature) => {
  if (existing.has(feature.id)) return
  await v1('POST', '/features', feature)
}
const groups = (await v1('GET', '/saved-groups?limit=100')).savedGroups ?? []
const group = async (name, body) =>
  groups.find((g) => g.name === name) ?? (await v1('POST', '/saved-groups', { name, ...body })).savedGroup

await v1('POST', '/attributes', { property: 'id', datatype: 'string', hashAttribute: true }).catch(() => {})
await v1('POST', '/attributes', { property: 'country', datatype: 'string' }).catch(() => {})
await v1('POST', '/attributes', { property: 'vipLevel', datatype: 'number' }).catch(() => {})

const vipsId = (await group('GB VIPs', { condition: JSON.stringify({ vipLevel: { $gte: 3 } }) })).id
const testersId = (await group('GB testers', { attributeKey: 'id', values: ['tester-1', 'tester-2'] })).id

// GrowthBook's REST API takes values as strings: raw for string features, JSON for the other types
const raw = (value) => (typeof value === 'string' ? value : JSON.stringify(value))
const force = (value, condition, extra = {}) => ({
  type: 'force', enabled: true, value: raw(value), condition: condition ? JSON.stringify(condition) : '', ...extra,
})

await createFeature({
  id: 'gb-new-checkout', owner: 'payments', valueType: 'boolean', defaultValue: 'false', description: 'New checkout (GB)',
  tags: ['checkout'],
  environments: {
    production: {
      enabled: true,
      rules: [
        force(true, null, { savedGroupTargeting: [{ matchType: 'any', savedGroups: [testersId] }] }),
        { type: 'rollout', enabled: true, value: 'true', coverage: 0.25, hashAttribute: 'id', condition: JSON.stringify({ country: 'BR' }) },
      ],
    },
  },
})
await createFeature({
  id: 'gb-lobby-layout', owner: 'casino', valueType: 'string', defaultValue: 'grid', description: 'Lobby layout (GB)',
  environments: {
    production: {
      enabled: true,
      rules: [force('carousel', { country: { $in: ['BR', 'PT'] } }, { savedGroupTargeting: [{ matchType: 'all', savedGroups: [vipsId] }] })],
    },
  },
})
await createFeature({
  id: 'gb-max-bet', owner: 'sportsbook', valueType: 'number', defaultValue: '1000', description: 'Max bet (GB)',
  environments: {
    production: {
      enabled: true,
      rules: [force(50000, null, { savedGroupTargeting: [{ matchType: 'all', savedGroups: [vipsId] }] }),
        force(0, null, { savedGroupTargeting: [{ matchType: 'none', savedGroups: [vipsId] }], condition: JSON.stringify({ country: 'XX' }) })],
    },
  },
})
await createFeature({
  id: 'gb-welcome-bonus', owner: 'payments', valueType: 'json', defaultValue: JSON.stringify({ enabled: false }),
  description: 'Welcome bonus (GB)',
  environments: { production: { enabled: true, rules: [force({ enabled: true, percent: 100 }, { country: 'BR' })] } },
})
await createFeature({
  id: 'gb-button-copy', owner: 'payments', valueType: 'string', defaultValue: 'Deposit', description: 'Button copy test (GB)',
  environments: {
    production: {
      enabled: true,
      rules: [{
        type: 'experiment', enabled: true, condition: '', trackingKey: 'gb-button-copy', hashAttribute: 'id', coverage: 1,
        value: [{ value: 'Deposit', weight: 0.5, name: 'Control' }, { value: 'Add funds', weight: 0.5, name: 'Add funds' }],
      }],
    },
  },
})
await createFeature({
  id: 'gb-dark-mode', owner: 'app', valueType: 'boolean', defaultValue: 'false', description: 'Disabled in production (GB)',
  environments: { production: { enabled: false, rules: [] } },
})

const connections = (await v1('GET', '/sdk-connections?limit=100')).connections ?? []
const connection = connections.find((c) => c.name === 'GB demo (production)')
  ?? (await v1('POST', '/sdk-connections', { name: 'GB demo (production)', language: 'javascript', environment: 'production' })).sdkConnection
console.log(`Local GrowthBook seeded. SDK connection client key: ${connection.key}`)
